// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui.Layouts;
using System.Threading.Tasks;

namespace BlazorBindings.Maui.Elements
{
    /// <summary>
    /// A Flexbox-like layout that lays out child elements in optionally wrappable rows or columns of child elements.
    /// </summary>
    public partial class FlexLayout : Layout
    {
        static FlexLayout()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets a value that controls how multiple rows or columns of child elements are aligned.
        /// </summary>
        [Parameter] public FlexAlignContent? AlignContent { get; set; }
        /// <summary>
        /// Gets or sets a value that controls how child elements are laid out within their row or column.
        /// </summary>
        /// <value>
        /// A value that controls how child elements are laid out within their row or column.
        /// </value>
        [Parameter] public FlexAlignItems? AlignItems { get; set; }
        /// <summary>
        /// Gets or sets the flex direction for child elements within this layout.
        /// </summary>
        /// <value>
        /// The flex direction for child elements within this layout.
        /// </value>
        [Parameter] public FlexDirection? Direction { get; set; }
        /// <summary>
        /// Gets or sets a value that that describes how child elements are justified when there is extra space around them.
        /// </summary>
        /// <value>
        /// A value that that describes how child elements are justified when there is extra space around them.
        /// </value>
        [Parameter] public FlexJustify? JustifyContent { get; set; }
        /// <summary>
        /// Gets or sets a value that controls whether the coordinates of child elements are specified in absolute or relative terms.
        /// </summary>
        /// <value>
        /// A value that controls whether the coordinates of child elements are specified in absolute or relative terms.
        /// </value>
        [Parameter] public FlexPosition? Position { get; set; }
        /// <summary>
        /// Gets or sets a value that controls whether and how child elements within this layout wrap.
        /// </summary>
        /// <value>
        /// A value that controls whether and how child elements within this layout wrap.
        /// </value>
        [Parameter] public FlexWrap? Wrap { get; set; }

        public new MC.FlexLayout NativeControl => (MC.FlexLayout)((BindableObject)this).NativeControl;

        protected override MC.FlexLayout CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(AlignContent):
                    if (!Equals(AlignContent, value))
                    {
                        AlignContent = (FlexAlignContent?)value;
                        NativeControl.AlignContent = AlignContent ?? (FlexAlignContent)MC.FlexLayout.AlignContentProperty.DefaultValue;
                    }
                    break;
                case nameof(AlignItems):
                    if (!Equals(AlignItems, value))
                    {
                        AlignItems = (FlexAlignItems?)value;
                        NativeControl.AlignItems = AlignItems ?? (FlexAlignItems)MC.FlexLayout.AlignItemsProperty.DefaultValue;
                    }
                    break;
                case nameof(Direction):
                    if (!Equals(Direction, value))
                    {
                        Direction = (FlexDirection?)value;
                        NativeControl.Direction = Direction ?? (FlexDirection)MC.FlexLayout.DirectionProperty.DefaultValue;
                    }
                    break;
                case nameof(JustifyContent):
                    if (!Equals(JustifyContent, value))
                    {
                        JustifyContent = (FlexJustify?)value;
                        NativeControl.JustifyContent = JustifyContent ?? (FlexJustify)MC.FlexLayout.JustifyContentProperty.DefaultValue;
                    }
                    break;
                case nameof(Position):
                    if (!Equals(Position, value))
                    {
                        Position = (FlexPosition?)value;
                        NativeControl.Position = Position ?? (FlexPosition)MC.FlexLayout.PositionProperty.DefaultValue;
                    }
                    break;
                case nameof(Wrap):
                    if (!Equals(Wrap, value))
                    {
                        Wrap = (FlexWrap?)value;
                        NativeControl.Wrap = Wrap ?? (FlexWrap)MC.FlexLayout.WrapProperty.DefaultValue;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
