// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui;
using System.Threading.Tasks;

namespace BlazorBindings.Maui.Elements
{
    public partial class Image : View
    {
        static Image()
        {
            RegisterAdditionalHandlers();
        }

        [Parameter] public Aspect? Aspect { get; set; }
        [Parameter] public bool? IsAnimationPlaying { get; set; }
        [Parameter] public bool? IsOpaque { get; set; }
        [Parameter] public MC.ImageSource Source { get; set; }

        public new MC.Image NativeControl => (MC.Image)((Element)this).NativeControl;

        protected override MC.Element CreateNativeElement() => new MC.Image();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Aspect):
                    if (!Equals(Aspect, value))
                    {
                        Aspect = (Aspect?)value;
                        NativeControl.Aspect = Aspect ?? (Aspect)MC.Image.AspectProperty.DefaultValue;
                    }
                    break;
                case nameof(IsAnimationPlaying):
                    if (!Equals(IsAnimationPlaying, value))
                    {
                        IsAnimationPlaying = (bool?)value;
                        NativeControl.IsAnimationPlaying = IsAnimationPlaying ?? (bool)MC.Image.IsAnimationPlayingProperty.DefaultValue;
                    }
                    break;
                case nameof(IsOpaque):
                    if (!Equals(IsOpaque, value))
                    {
                        IsOpaque = (bool?)value;
                        NativeControl.IsOpaque = IsOpaque ?? (bool)MC.Image.IsOpaqueProperty.DefaultValue;
                    }
                    break;
                case nameof(Source):
                    if (!Equals(Source, value))
                    {
                        Source = (MC.ImageSource)value;
                        NativeControl.Source = Source;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
