// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements.Handlers;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Maui;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BlazorBindings.Maui.Elements
{
    public abstract partial class ItemsView<T> : View
    {
        static ItemsView()
        {
            ElementHandlerRegistry.RegisterPropertyContentHandler<ItemsView<T>>(nameof(EmptyView),
                (renderer, parent, component) => new ContentPropertyHandler<MC.ItemsView>((x, value) => x.EmptyView = (object)value));
            ElementHandlerRegistry.RegisterPropertyContentHandler<ItemsView<T>>(nameof(ItemTemplate),
                (renderer, parent, component) => new DataTemplatePropertyHandler<MC.ItemsView, T>(component,
                    (x, dataTemplate) => x.ItemTemplate = dataTemplate));
            RegisterAdditionalHandlers();
        }

        [Parameter] public ScrollBarVisibility? HorizontalScrollBarVisibility { get; set; }
        [Parameter] public IEnumerable<T> ItemsSource { get; set; }
        [Parameter] public MC.ItemsUpdatingScrollMode? ItemsUpdatingScrollMode { get; set; }
        [Parameter] public int? RemainingItemsThreshold { get; set; }
        [Parameter] public ScrollBarVisibility? VerticalScrollBarVisibility { get; set; }
        [Parameter] public RenderFragment EmptyView { get; set; }
        [Parameter] public RenderFragment<T> ItemTemplate { get; set; }
        [Parameter] public EventCallback<MC.ScrollToRequestEventArgs> OnScrollToRequested { get; set; }
        [Parameter] public EventCallback<MC.ItemsViewScrolledEventArgs> OnScrolled { get; set; }
        [Parameter] public EventCallback OnRemainingItemsThresholdReached { get; set; }

        public new MC.ItemsView NativeControl => (MC.ItemsView)((Element)this).NativeControl;


        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(HorizontalScrollBarVisibility):
                    if (!Equals(HorizontalScrollBarVisibility, value))
                    {
                        HorizontalScrollBarVisibility = (ScrollBarVisibility?)value;
                        NativeControl.HorizontalScrollBarVisibility = HorizontalScrollBarVisibility ?? (ScrollBarVisibility)MC.ItemsView.HorizontalScrollBarVisibilityProperty.DefaultValue;
                    }
                    break;
                case nameof(ItemsSource):
                    if (!Equals(ItemsSource, value))
                    {
                        ItemsSource = (IEnumerable<T>)value;
                        NativeControl.ItemsSource = ItemsSource;
                    }
                    break;
                case nameof(ItemsUpdatingScrollMode):
                    if (!Equals(ItemsUpdatingScrollMode, value))
                    {
                        ItemsUpdatingScrollMode = (MC.ItemsUpdatingScrollMode?)value;
                        NativeControl.ItemsUpdatingScrollMode = ItemsUpdatingScrollMode ?? (MC.ItemsUpdatingScrollMode)MC.ItemsView.ItemsUpdatingScrollModeProperty.DefaultValue;
                    }
                    break;
                case nameof(RemainingItemsThreshold):
                    if (!Equals(RemainingItemsThreshold, value))
                    {
                        RemainingItemsThreshold = (int?)value;
                        NativeControl.RemainingItemsThreshold = RemainingItemsThreshold ?? (int)MC.ItemsView.RemainingItemsThresholdProperty.DefaultValue;
                    }
                    break;
                case nameof(VerticalScrollBarVisibility):
                    if (!Equals(VerticalScrollBarVisibility, value))
                    {
                        VerticalScrollBarVisibility = (ScrollBarVisibility?)value;
                        NativeControl.VerticalScrollBarVisibility = VerticalScrollBarVisibility ?? (ScrollBarVisibility)MC.ItemsView.VerticalScrollBarVisibilityProperty.DefaultValue;
                    }
                    break;
                case nameof(EmptyView):
                    EmptyView = (RenderFragment)value;
                    break;
                case nameof(ItemTemplate):
                    ItemTemplate = (RenderFragment<T>)value;
                    break;
                case nameof(OnScrollToRequested):
                    if (!Equals(OnScrollToRequested, value))
                    {
                        void NativeControlScrollToRequested(object sender, MC.ScrollToRequestEventArgs e) => InvokeAsync(() => OnScrollToRequested.InvokeAsync(e));

                        OnScrollToRequested = (EventCallback<MC.ScrollToRequestEventArgs>)value;
                        NativeControl.ScrollToRequested -= NativeControlScrollToRequested;
                        NativeControl.ScrollToRequested += NativeControlScrollToRequested;
                    }
                    break;
                case nameof(OnScrolled):
                    if (!Equals(OnScrolled, value))
                    {
                        void NativeControlScrolled(object sender, MC.ItemsViewScrolledEventArgs e) => InvokeAsync(() => OnScrolled.InvokeAsync(e));

                        OnScrolled = (EventCallback<MC.ItemsViewScrolledEventArgs>)value;
                        NativeControl.Scrolled -= NativeControlScrolled;
                        NativeControl.Scrolled += NativeControlScrolled;
                    }
                    break;
                case nameof(OnRemainingItemsThresholdReached):
                    if (!Equals(OnRemainingItemsThresholdReached, value))
                    {
                        void NativeControlRemainingItemsThresholdReached(object sender, EventArgs e) => InvokeAsync(() => OnRemainingItemsThresholdReached.InvokeAsync());

                        OnRemainingItemsThresholdReached = (EventCallback)value;
                        NativeControl.RemainingItemsThresholdReached -= NativeControlRemainingItemsThresholdReached;
                        NativeControl.RemainingItemsThresholdReached += NativeControlRemainingItemsThresholdReached;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty(builder, sequence++, typeof(ItemsView<T>), EmptyView);
            RenderTreeBuilderHelper.AddDataTemplateProperty(builder, sequence++, typeof(ItemsView<T>), ItemTemplate);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
