// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using System.Threading.Tasks;

#pragma warning disable CA2252

namespace BlazorBindings.Maui.Elements
{
    /// <summary>
    /// Corresponds to a <see cref="T:Microsoft.Maui.Controls.ContentPage" /> contained in a <see cref="T:Microsoft.Maui.Controls.ShellSection" />.
    /// </summary>
    public partial class ShellContent : BaseShellItem
    {
        static ShellContent()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Add <see cref="T:Microsoft.Maui.Controls.MenuItem" /> instances to flyout.
        /// </summary>
        [Parameter] public RenderFragment MenuItems { get; set; }

        public new MC.ShellContent NativeControl => (MC.ShellContent)((BindableObject)this).NativeControl;

        protected override MC.ShellContent CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(MenuItems):
                    MenuItems = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddListContentProperty<MC.ShellContent, MC.MenuItem>(builder, sequence++, MenuItems, x => x.MenuItems);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
