// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

namespace BlazorBindings.Maui.Elements
{
    public partial class ShellSection : ShellGroupItem
    {
        static ShellSection()
        {
            RegisterAdditionalHandlers();
        }

        public new MC.ShellSection NativeControl => (MC.ShellSection)((BindableObject)this).NativeControl;

        protected override MC.ShellSection CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
