// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

namespace BlazorBindings.Maui.Elements
{
    /// <summary>
    /// A <see cref="T:Microsoft.Maui.Controls.View" /> control that inputs a discrete value, constrained to a range.
    /// </summary>
    public partial class Stepper : View
    {
        static Stepper()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the increment by which Value is increased or decreased.
        /// </summary>
        /// <value>
        /// A double.
        /// </value>
        [Parameter] public double? Increment { get; set; }
        /// <summary>
        /// Gets or sets the maximum selectable value.
        /// </summary>
        /// <value>
        /// A double.
        /// </value>
        [Parameter] public double? Maximum { get; set; }
        /// <summary>
        /// Gets or sets the minimum selectabel value.
        /// </summary>
        /// <value>
        /// A double.
        /// </value>
        [Parameter] public double? Minimum { get; set; }
        /// <summary>
        /// Gets or sets the current value.
        /// </summary>
        /// <value>
        /// A double.
        /// </value>
        [Parameter] public double? Value { get; set; }
        [Parameter] public EventCallback<double> ValueChanged { get; set; }

        public new MC.Stepper NativeControl => (MC.Stepper)((BindableObject)this).NativeControl;

        protected override MC.Stepper CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Increment):
                    if (!Equals(Increment, value))
                    {
                        Increment = (double?)value;
                        NativeControl.Increment = Increment ?? (double)MC.Stepper.IncrementProperty.DefaultValue;
                    }
                    break;
                case nameof(Maximum):
                    if (!Equals(Maximum, value))
                    {
                        Maximum = (double?)value;
                        NativeControl.Maximum = Maximum ?? (double)MC.Stepper.MaximumProperty.DefaultValue;
                    }
                    break;
                case nameof(Minimum):
                    if (!Equals(Minimum, value))
                    {
                        Minimum = (double?)value;
                        NativeControl.Minimum = Minimum ?? (double)MC.Stepper.MinimumProperty.DefaultValue;
                    }
                    break;
                case nameof(Value):
                    if (!Equals(Value, value))
                    {
                        Value = (double?)value;
                        NativeControl.Value = Value ?? (double)MC.Stepper.ValueProperty.DefaultValue;
                    }
                    break;
                case nameof(ValueChanged):
                    if (!Equals(ValueChanged, value))
                    {
                        void NativeControlValueChanged(object sender, MC.ValueChangedEventArgs e)
                        {
                            var value = NativeControl.Value;
                            Value = value;
                            InvokeEventCallback(ValueChanged, value);
                        }

                        ValueChanged = (EventCallback<double>)value;
                        NativeControl.ValueChanged -= NativeControlValueChanged;
                        NativeControl.ValueChanged += NativeControlValueChanged;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
