// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

namespace BlazorBindings.Maui.Elements
{
    /// <summary>
    /// A logical and visible section of a <see cref="T:Microsoft.Maui.Controls.TableView" />.
    /// </summary>
    public partial class TableSection : TableSectionBase
    {
        static TableSection()
        {
            RegisterAdditionalHandlers();
        }

        public new MC.TableSection NativeControl => (MC.TableSection)((BindableObject)this).NativeControl;

        protected override MC.TableSection CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
