// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements.Handlers;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using System.Threading.Tasks;

namespace BlazorBindings.Maui.Elements
{
    public partial class TemplatedView : BlazorBindings.Maui.Elements.Compatibility.Layout
    {
        static TemplatedView()
        {
            ElementHandlerRegistry.RegisterPropertyContentHandler<TemplatedView>(nameof(ControlTemplate),
                (renderer, parent, component) => new ControlTemplatePropertyHandler<MC.TemplatedView>(component,
                    (x, controlTemplate) => x.ControlTemplate = controlTemplate));
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the control template that is used to display content.
        /// </summary>
        [Parameter] public RenderFragment ControlTemplate { get; set; }

        public new MC.TemplatedView NativeControl => (MC.TemplatedView)((BindableObject)this).NativeControl;

        protected override MC.TemplatedView CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(ControlTemplate):
                    ControlTemplate = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddControlTemplateProperty(builder, sequence++, typeof(TemplatedView), ControlTemplate);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
