// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

namespace BlazorBindings.Maui.Elements
{
    public partial class ToolbarItem : MenuItem
    {
        static ToolbarItem()
        {
            RegisterAdditionalHandlers();
        }

        [Parameter] public MC.ToolbarItemOrder? Order { get; set; }
        [Parameter] public int? Priority { get; set; }

        public new MC.ToolbarItem NativeControl => (MC.ToolbarItem)((Element)this).NativeControl;

        protected override MC.Element CreateNativeElement() => new MC.ToolbarItem();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Order):
                    if (!Equals(Order, value))
                    {
                        Order = (MC.ToolbarItemOrder?)value;
                        NativeControl.Order = Order ?? default;
                    }
                    break;
                case nameof(Priority):
                    if (!Equals(Priority, value))
                    {
                        Priority = (int?)value;
                        NativeControl.Priority = Priority ?? default;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
