// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.AspNetCore.Components.Rendering;

#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements
{
    /// <summary>
    /// Base class for controls which decorate a single child control.
    /// </summary>
    public partial class Decorator : Control
    {
        static Decorator()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the padding to place around the <see cref="P:Avalonia.Controls.Decorator.Child" /> control.
        /// </summary>
        [Parameter] public global::Avalonia.Thickness? Padding { get; set; }
        /// <summary>
        /// Gets or sets the decorated control.
        /// </summary>
        [Parameter] public RenderFragment ChildContent { get; set; }

        public new AC.Decorator NativeControl => (AC.Decorator)((BindableObject)this).NativeControl;

        protected override AC.Decorator CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Padding):
                    if (!Equals(Padding, value))
                    {
                        Padding = (global::Avalonia.Thickness?)value;
                        NativeControl.Padding = Padding ?? (global::Avalonia.Thickness)AC.Decorator.PaddingProperty.GetDefaultValue(AC.Decorator.PaddingProperty.OwnerType);
                    }
                    break;
                case nameof(ChildContent):
                    ChildContent = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty<AC.Decorator>(builder, sequence++, ChildContent,
                (nativeControl, data) => nativeControl.Child = (AC.Control)data);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
