// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using System.Collections;
using System.Threading.Tasks;

#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements
{
    /// <summary>
    /// Displays a collection of items.
    /// </summary>
    public partial class ItemsControl<T> : BlazorBindings.AvaloniaBindings.Elements.Primitives.TemplatedControl
    {

        /// <summary>
        /// Gets or sets the panel used to display the items.
        /// </summary>
        [Parameter] public RenderFragment ItemsPanel { get; set; }
        
        protected override bool HandleAdditionalParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(ItemsPanel):
                    ItemsPanel = (RenderFragment)value;
                    return true;

                default:
                    return base.HandleAdditionalParameter(name, value);
            }
        }


        protected override void RenderAdditionalPartialElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalPartialElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddSyncDataTemplateProperty<Avalonia.Controls.ItemsControl, T>(builder, sequence++, ItemTemplate, (x, template) => x.ItemTemplate = template);
        }
    }
}
