// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>



#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements
{
    /// <summary>
    /// A top-level menu control.
    /// </summary>
    public partial class Menu<T> : MenuBase<T>
    {
        static Menu()
        {
            RegisterAdditionalHandlers();
        }

        public new AC.Menu NativeControl => (AC.Menu)((AvaloniaObject)this).NativeControl;

        protected override AC.Menu CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
