// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>



#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements
{
    /// <summary>
    /// Defines an area within which you can position and align child objects in relation to each other or the parent panel.
    /// </summary>
    public partial class RelativePanel : Panel
    {
        static RelativePanel()
        {
            RegisterAdditionalHandlers();
        }

        public new AC.RelativePanel NativeControl => (AC.RelativePanel)((BindableObject)this).NativeControl;

        protected override AC.RelativePanel CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
