// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>



#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements
{
    /// <summary>
    /// A control which pops up a hint when a control is hovered.
    /// </summary>
    public partial class ToolTip : ContentControl
    {
        static ToolTip()
        {
            RegisterAdditionalHandlers();
        }

        public new AC.ToolTip NativeControl => (AC.ToolTip)((AvaloniaObject)this).NativeControl;

        protected override AC.ToolTip CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
