// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using ACD = Avalonia.Controls.Documents;
using BlazorBindings.AvaloniaBindings.Elements;
using BlazorBindings.Core;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements.Documents
{
    /// <summary>
    /// Span element used for grouping other Inline elements.
    /// </summary>
    public partial class Span : Inline
    {
        static Span()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the inlines.
        /// </summary>
        [Parameter] public ACD.InlineCollection Inlines { get; set; }

        public new ACD.Span NativeControl => (ACD.Span)((BindableObject)this).NativeControl;

        protected override ACD.Span CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Inlines):
                    if (!Equals(Inlines, value))
                    {
                        Inlines = (ACD.InlineCollection)value;
                        NativeControl.Inlines = Inlines;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
