// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements.Shapes
{
    public partial class Ellipse : Shape
    {
        protected override RenderFragment GetChildContent()
        {
            return ChildContent;
        }
        [Parameter] public RenderFragment ChildContent { get; set; }

        protected override bool HandleAdditionalParameter(string name, object value)
        {
            if(name == "ChildContent")
            {
                ChildContent = value as RenderFragment;
                return true;
            }
            return base.HandleAdditionalParameter(name, value);
        }
    }

    public static class EllipseExtensions
    {
        public static Ellipse ToolTip_TipExtension(this Ellipse self, string text)
        {
            self.AttachedProperties["ToolTip.Tip"] = text;

            return self;
        }
    }
}
