// <auto-generated>
//     This code was generated by a BlazorBindings.Avalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using AI = Avalonia.Interactivity;
using BlazorBindings.AvaloniaBindings.Elements;
using BlazorBindings.Core;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

#pragma warning disable CA2252

namespace BlazorBindings.AvaloniaBindings.Elements.Interactivity
{
    /// <summary>
    /// Base class for objects that raise routed events.
    /// </summary>
    public partial class Interactive : BlazorBindings.AvaloniaBindings.Elements.Layout.Layoutable
    {
        static Interactive()
        {
            RegisterAdditionalHandlers();
        }

        public new AI.Interactive NativeControl => (AI.Interactive)((BindableObject)this).NativeControl;

        protected override AI.Interactive CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
